// Code generated by tygo. DO NOT EDIT.

//////////
// source: check.go

export interface Violation {
  Rule: string;
  Detail: string;
  Severity: string;
}

//////////
// source: policy.go

export type BudgetScope = string;
export const ScopeIdentity: BudgetScope = "identity";
export const ScopeProvider: BudgetScope = "provider";
export const ScopeGlobal: BudgetScope = "global";
export interface Budget {
  daily_limit: number /* int */;
  monthly_limit: number /* int */;
  enabled: boolean;
}

//////////
// source: status.go

export interface BudgetStatus {
  scope: BudgetScope;
  id: string;
  budget: Budget;
  daily_used: number /* int */;
  monthly_used: number /* int */;
}

//////////
// source: topics.go

/**
 * Topic is a blockable subject-matter category. Keyword-based
 * matching for v1, same philosophy as detector.ContentRule — every
 * match is explainable to an auditor as "this exact pattern fired,"
 * which matters more for a compliance product than raw recall would.
 * Source is cited on every topic so a policy decision can always be
 * traced back to why it exists, not just that it exists.
 */
export interface Topic {
  Key: string;
  Name: string;
  Source: string;
  Keywords: string[];
}
