// Code generated by tygo. DO NOT EDIT.

//////////
// source: anomalies.go

export interface Anomaly {
  id: string;
  request_id: string;
  rule: string;
  detail: string;
  category: string;
  severity: string;
  status: string;
  created_at: any /* time.Time */;
}
export interface AnomalyFilter {
  Category: string;
  Severity: string;
  Status: string;
}

//////////
// source: identities.go

export interface Identity {
  id: string;
  name: string;
  created_at: any /* time.Time */;
}

//////////
// source: requests.go

export interface Request {
  id: string;
  identity_id?: string;
  provider: string;
  model: string;
  prompt_tokens: number /* int */;
  completion_tokens: number /* int */;
  latency_ms: number /* int */;
  status_code: number /* int */;
  created_at: any /* time.Time */;
}
